//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformationRetrieval
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dic
    {
        public int Id { get; set; }
        public Nullable<int> termID { get; set; }
        public Nullable<int> docID { get; set; }
        public Nullable<int> freq { get; set; }
        public Nullable<double> weight { get; set; }
    
        public virtual Doc Doc { get; set; }
        public virtual Term Term { get; set; }
    }
}
