//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformationRetrieval
{
    using System;
    using System.Collections.Generic;
    
    public partial class index
    {
        public int id { get; set; }
        public int Doc_Freq { get; set; }
        public int weight { get; set; }
    
        public virtual Doc Doc { get; set; }
        public virtual Term Term { get; set; }
    }
}
